import { VercelRequest, VercelResponse } from '@vercel/node';
import { sql } from '@vercel/postgres';

export default async function handler(
  request: VercelRequest,
  response: VercelResponse,
) {
  try {
    const result =
      await sql`DROP TABLE IF EXISTS ideas;
      CREATE TABLE ideas (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      ideaName TEXT NOT NULL,
      ideaSummary TEXT NOT NULL,
      authorName TEXT NOT NULL,
      email TEXT NOT NULL,
      claimed boolean not null,
      submitted boolean not null
);;`;
    return response.status(200).json({ result });
  } catch (error) {
    return response.status(500).json({ error });
  }
}